name: run notebook (individual)

on:
  workflow_dispatch:
    inputs:
      notebook:
        description: "Path to the notebook to run"
        required: true
        type: choice
        options: ${{ fromYaml(readFile('.github/workflows/notebooks.yaml')) }}
      version:
        description: "latest/stable/semver/branch"
        required: true
        type: string

jobs:
  notebook:
    uses: ./.github/workflows/run_notebook.yaml
    with:
      notebook: ${{ inputs.notebook }}
      version: ${{ inputs.version }}
